
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('DMC00000', '직영공사', '직영공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('DMC00001', '안전반장', '안전반장', 'DMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('DMC00002', '전기반장', '전기반장', 'DMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('DMC00003', '직영반장', '직영반장', 'DMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00000', '설비공사', '설비공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00001', '기계설치', '기계설치', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00002', '덕  트', '덕  트', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00003', '보  온', '보  온', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00004', '설비배관', '설비배관', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00005', '설비용접', '설비용접', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00006', '설비조공', '설비조공', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00007', '쓰레기 이송설비', '쓰레기 이송설비', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00008', '전  공', '전  공', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EQC00009', '코  어', '코  어', 'EQC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETC00000', '기타공사', '기타공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETC00001', '바닥  배수판', '바닥  배수판', 'ETC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETC00002', '벽체  배수판', '벽체  배수판', 'ETC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETC00003', '입주청소', '입주청소', 'ETC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00000', '전기공사', '전기공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00001', 'CCTV', 'CCTV', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00002', '관리자', '관리자', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00003', '관리자', '관리자', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00004', '내선전공', '내선전공', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00005', '등기구', '등기구', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00006', '무선통신', '무선통신', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00007', '방송', '방송', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00008', '배관공', '배관공', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00009', '배전전', '배전전', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00010', '비상벨', '비상벨', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00011', '소방전기', '소방전기', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00012', '엘레 베이터', '엘레 베이터', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00013', '인터폰', '인터폰', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00014', '저압 케이블', '저압 케이블', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00015', '전력제어', '전력제어', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00016', '조명제어', '조명제어', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00017', '주차관제', '주차관제', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00018', '직영반장', '직영반장', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00019', '직영반장', '직영반장', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00020', '통신', '통신', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00021', '통신내선', '통신내선', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00022', '통신케이블', '통신케이블', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('ETN00023', '특고압케이블', '특고압케이블', 'ETN00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00000', '토공사 및 지정공사', '토공사 및 지정공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00001', '경계석 설치', '경계석 설치', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00002', '관리자', '관리자', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00003', '어스앙카', '어스앙카', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00004', '우, 오수 관로', '우, 오수 관로', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00005', '직영반장', '직영반장', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00006', '철 골 가시설', '철 골 가시설', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00007', '토목형틀', '토목형틀', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('EWC00008', '포  장', '포  장', 'EWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00000', '가구공사', '가구공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00001', '관리자', '관리자', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00002', '시스템 선반', '시스템 선반', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00003', '욕실가구', '욕실가구', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00004', '인조대리석 설치', '인조대리석 설치', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00005', '일반가구', '일반가구', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00006', '주방가구', '주방가구', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00007', '주방일반가구도어', '주방일반가구도어', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00008', '직영반장', '직영반장', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('FTC00009', '하드웨어', '하드웨어', 'FTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00000', '유리공사', '유리공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00001', '관리자', '관리자', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00002', '내부코킹', '내부코킹', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00003', '백페인트', '백페인트', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00004', '외부코킹', '외부코킹', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00005', '유리설치', '유리설치', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('GLC00006', '직영반장', '직영반장', 'GLC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00000', '내장 및 수장공사', '내장 및 수장공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00001', '관리자', '관리자', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00002', '내장/CRC 보  드', '내장/CRC 보  드', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00003', '내장/걸레받이', '내장/걸레받이', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00004', '내장/경량칸막이', '내장/경량칸막이', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00005', '내장/그라스 크로스', '내장/그라스 크로스', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00006', '내장/단열재 설  치', '내장/단열재 설  치', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00007', '내장/먹매김 (내장)', '내장/먹매김 (내장)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00008', '내장/목 천정', '내장/목 천정', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00009', '내장/몰  딩', '내장/몰  딩', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00010', '내장/석고보드(경량)', '내장/석고보드(경량)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00011', '내장/석고보드(합지)', '내장/석고보드(합지)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00012', '내장/아트월', '내장/아트월', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00013', '내장/운  반(내장)', '내장/운  반(내장)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00014', '수장/ABS (욕실)', '수장/ABS (욕실)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00015', '수장/SGP', '수장/SGP', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00016', '수장/경 량 칸막이', '수장/경 량 칸막이', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00017', '수장/경량천정', '수장/경량천정', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00018', '수장/도  배', '수장/도  배', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00019', '수장/디럭스 바닥타일', '수장/디럭스 바닥타일', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00020', '수장/마루판', '수장/마루판', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00021', '수장/비닐시트 (장판)', '수장/비닐시트 (장판)', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00022', '수장/초배지', '수장/초배지', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00023', '수장/퍼  티', '수장/퍼  티', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('IWC00024', '직영반장', '직영반장', 'IWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00000', '조경공사', '조경공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00001', 'SG블록 포 장', 'SG블록 포 장', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00002', '고무칩 포장', '고무칩 포장', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00003', '고압블록 포 장', '고압블록 포 장', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00004', '관리자', '관리자', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00005', '놀이기구', '놀이기구', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00006', '목재 사이딩', '목재 사이딩', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00007', '목재루버', '목재루버', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00008', '식  재', '식  재', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00009', '잔  디', '잔  디', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00010', '전지작업', '전지작업', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00011', '직영반장', '직영반장', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('LSC00012', '휀스설치', '휀스설치', 'LSC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00000', '금속공사', '금속공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00001', '과 속 방지턱', '과 속 방지턱', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00002', '관리자', '관리자', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00003', '반사경', '반사경', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00004', '샤워부스', '샤워부스', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00005', '용 접 (금속)', '용 접 (금속)', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00006', '자동문 ', '자동문 ', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00007', '잡  철', '잡  철', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00008', '직영반장', '직영반장', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00009', '징크', '징크', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00010', '철골설치', '철골설치', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00011', '카스토퍼 코너보호', '카스토퍼 코너보호', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('MTC00012', '하드웨어', '하드웨어', 'MTC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00000', '판넬 및 몰딩공사', '판넬 및 몰딩공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00001', 'ALC판넬', 'ALC판넬', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00002', 'AL판넬', 'AL판넬', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00003', '경량콘크 리트판넬', '경량콘크 리트판넬', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00004', '관리자', '관리자', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00005', '드라이 비트', '드라이 비트', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00006', '샌드위치 판 넬', '샌드위치 판 넬', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00007', '외부몰딩', '외부몰딩', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('PMC00008', '직영반장', '직영반장', 'PMC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00000', '철근콘크리트', '철근콘크리트', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00001', '견 출 (로프)', '견 출 (로프)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00002', '견 출 (일반)', '견 출 (일반)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00003', '관리자', '관리자', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00004', '데  크', '데  크', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00005', '먹매김', '먹매김', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00006', '목 수 ( AL폼)', '목 수 ( AL폼)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00007', '목 수 (유로폼)', '목 수 (유로폼)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00008', '비계공 (단관)', '비계공 (단관)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00009', '비계공 (시스템)', '비계공 (시스템)', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00010', '직영반장', '직영반장', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00011', '철  거', '철  거', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00012', '철  근', '철  근', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00013', '콘크리트', '콘크리트', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('RFC00014', '할  석', '할  석', 'RFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00000', '석재 및 코킹공사', '석재 및 코킹공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00001', '관리자', '관리자', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00002', '내부코킹', '내부코킹', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00003', '내부코킹', '내부코킹', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00004', '바닥석재', '바닥석재', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00005', '벽체석재', '벽체석재', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00006', '보  양', '보  양', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00007', '외부코킹', '외부코킹', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00008', '외부코킹', '외부코킹', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00009', '운 반 (석재)', '운 반 (석재)', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00010', '조 공 (석재)', '조 공 (석재)', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00011', '줄  눈', '줄  눈', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00012', '직영반장', '직영반장', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SCC00013', '트러스팀', '트러스팀', 'SCC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00000', '철골공사', '철골공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00001', '관리자', '관리자', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00002', '데  크', '데  크', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00003', '스터드', '스터드', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00004', '앙카볼트', '앙카볼트', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00005', '용  접', '용  접', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00006', '직영반장', '직영반장', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SFC00007', '철골설치', '철골설치', 'SFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00000', '도장공사', '도장공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00001', '관리자', '관리자', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00002', '내부도장', '내부도장', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00003', '내화  페인트', '내화  페인트', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00004', '내화뿜칠', '내화뿜칠', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00005', '무늬코트', '무늬코트', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00006', '바닥도장', '바닥도장', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00007', '외부도장(로프)', '외부도장(로프)', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00008', '직영반장', '직영반장', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00009', '천  정 단열뿜칠', '천  정 단열뿜칠', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00010', '천정우레 탄뿜칠', '천정우레 탄뿜칠', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00011', '특화뿜칠', '특화뿜칠', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('STC00012', '퍼  티', '퍼  티', 'STC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('SVC00000', '용역', '용역', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00000', '창호공사', '창호공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00001', 'AL창호', 'AL창호', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00002', 'PL창호', 'PL창호', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00003', '관리자', '관리자', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00004', '배연창 연동제어', '배연창 연동제어', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00005', '직영반장', '직영반장', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WDC00006', '하드웨어', '하드웨어', 'WDC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00000', '습식공사', '습식공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00001', '관리자', '관리자', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00002', '미장/갈매기미장', '미장/갈매기미장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00003', '미장/견  출', '미장/견  출', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00004', '미장/견  출 외부로프', '미장/견  출 외부로프', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00005', '미장/기포타설', '미장/기포타설', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00006', '미장/단열몰탈', '미장/단열몰탈', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00007', '미장/몰탈바닥미장', '미장/몰탈바닥미장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00008', '미장/미장조공', '미장/미장조공', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00009', '미장/벽미장', '미장/벽미장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00010', '미장/사  춤', '미장/사  춤', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00011', '미장/수지미장', '미장/수지미장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00012', '미장/층  간소음재', '미장/층  간소음재', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00013', '미장/컷  팅', '미장/컷  팅', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00014', '미장/콘크리트 바닥미장', '미장/콘크리트 바닥미장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00015', '방수/방수조공', '방수/방수조공', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00016', '방수/복합방수', '방수/복합방수', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00017', '방수/액체방수', '방수/액체방수', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00018', '방수/우레탄 방수', '방수/우레탄 방수', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00019', '방수/파  취', '방수/파  취', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00020', '조적/ALC', '조적/ALC', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00021', '조적/단열재', '조적/단열재', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00022', '조적/벽  돌', '조적/벽  돌', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00023', '조적/블 록', '조적/블 록', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00024', '조적/운반 (조적)', '조적/운반 (조적)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00025', '조적/조공 (조적)', '조적/조공 (조적)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00026', '조적/치장줄눈', '조적/치장줄눈', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00027', '직영반장', '직영반장', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00028', '타일/바닥타일', '타일/바닥타일', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00029', '타일/벽   (압착)', '타일/벽   (압착)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00030', '타일/벽  (에폭시)', '타일/벽  (에폭시)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00031', '타일/벽(떠붙임)', '타일/벽(떠붙임)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00032', '타일/보양', '타일/보양', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00033', '타일/운  반(타일)', '타일/운  반(타일)', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WFC00034', '타일/줄눈', '타일/줄눈', 'WFC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00000', '목창호공사', '목창호공사', null,  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00001', '관리자', '관리자', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00002', '도어설치', '도어설치', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00003', '문  틀(가틀)', '문  틀(가틀)', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00004', '문  틀(본틀)', '문  틀(본틀)', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00005', '슬라이딩 도 어', '슬라이딩 도 어', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00006', '직영반장', '직영반장', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00007', '포켓도어', '포켓도어', 'WWC00000',  'admin',  'admin');
INSERT INTO work_section (section_cd, section_name, description, parent_section_cd, creator, updater) VALUES ('WWC00008', '하드웨어', '하드웨어', 'WWC00000',  'admin',  'admin');


